version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: EvolvAi
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: localhost
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
