default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] || 'admin_user' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'admin' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432

development:
  <<: *default
  database: EvolvAi

test:
  <<: *default
  database: EvolvAi

production:
  <<: *default
  database: your_app_production
  username: <%= ENV['POSTGRES_USER'] || 'admin_user' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'admin' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432
